### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by llb4ll** [LineageOS/android_device_bq_gohan#1]
What are the next steps for gohan?

My last info is, that the build works but there are still issues with the serial and the audio.

I would love to help with some testing. Is it safe (in terms of fully reversable) to build and flash the image? Unfortunately I can only test on my main device.

**Comment by stucki** [comment]
@llb4ll Please take another look at this repository, as it has been updated just recently...

**Comment by llb4ll** [comment]
Awesome, thanks!
